[build]
command = "npx nx build @react-monorepo/trucksync"
publish = "apps/trucksync/dist"

[[plugins]]
package = "netlify-plugin-nx-skip-build"

[build.environment]
NODE_VERSION = "22"

[context.production.environment]
NODE_ENV = "production"
